In [19]:
#Importando Bibliotecas
import pandas as pd
import numpy as np
import os
from pathlib import Path

In [20]:
#Importando as tábuas com os qx
qx_morta = pd.read_csv(str(Path(os.getcwd())) + '\\Tábuas\\tb_mortalidade.csv', encoding='UTF-8', sep=';')
qx_morta_inv = pd.read_csv(str(Path(os.getcwd())) + '\\Tábuas\\tb_mortalidade_inv.csv', encoding='UTF-8', sep=';')
qx_entrada_inv = pd.read_csv(str(Path(os.getcwd())) + '\\Tábuas\\tb_entrada_inv.csv', encoding='UTF-8', sep=';')
qx_morbidez = pd.read_csv(str(Path(os.getcwd())) + '\\Tábuas\\tb_morbidez.csv', encoding='UTF-8', sep=';')

In [21]:
#Calculando os px
px_morta = (1 - qx_morta)
px_morta_inv = (1 - qx_morta_inv)
px_entrada_inv = (1 - qx_entrada_inv)
px_morbidez = (1 - qx_morbidez)

In [22]:
#Calculando os dx e lx
dx_morta = pd.DataFrame(columns=qx_morta.columns)
dx_morta_inv = pd.DataFrame(columns=qx_morta_inv.columns)
dx_entrada_inv = pd.DataFrame(columns=qx_entrada_inv.columns)
dx_morbidez = pd.DataFrame(columns=qx_morbidez.columns)

lx_morta = pd.DataFrame(columns=qx_morta.columns)
lx_morta_inv = pd.DataFrame(columns=qx_morta_inv.columns)
lx_entrada_inv = pd.DataFrame(columns=qx_entrada_inv.columns)
lx_morbidez = pd.DataFrame(columns=qx_morbidez.columns)

for c in range(127):
    if c >= 1:
        lx_morta.loc[c] = lx_morta.loc[c-1] - dx_morta.loc[c-1]
        lx_morta_inv.loc[c] = lx_morta_inv.loc[c-1] - dx_morta_inv.loc[c-1]
        lx_entrada_inv.loc[c] = lx_entrada_inv.loc[c-1] - dx_entrada_inv.loc[c-1]
        lx_morbidez.loc[c] = lx_morbidez.loc[c-1] - dx_morbidez.loc[c-1]

        dx_morta.loc[c] = lx_morta.loc[c] * qx_morta.loc[c]
        dx_morta_inv.loc[c] = lx_morta_inv.loc[c] * qx_morta_inv.loc[c]
        dx_entrada_inv.loc[c] = lx_entrada_inv.loc[c] * qx_entrada_inv.loc[c]
        dx_morbidez.loc[c] = lx_morbidez.loc[c] * qx_morbidez.loc[c]

    else:
        lx_morta.loc[c] = 100000
        lx_morta_inv.loc[c] = 100000
        lx_entrada_inv.loc[c] = 100000
        lx_morbidez.loc[c] = 100000

        dx_morta.loc[c] = lx_morta.loc[c] * qx_morta.loc[c]
        dx_morta_inv.loc[c] = lx_morta_inv.loc[c] * qx_morta_inv.loc[c]
        dx_entrada_inv.loc[c] = lx_entrada_inv.loc[c] * qx_entrada_inv.loc[c]
        dx_morbidez.loc[c] = lx_morbidez.loc[c] * qx_morbidez.loc[c]

In [35]:
#Calculando as Comutações Dx
Dx_morta = pd.DataFrame(columns=qx_morta.columns)
tx_juros = 0.06
Dx_morta = lx_morta*qx_morta
Dx_morta

,ALLG-72,AMERICAN EXPERIENCE,AT2000 (Suavizada 10%)_FEM,AT2000 (Suavizada 10%)_MAS,AT-2000 FEMALE,AT-2000 MALE,AT-49 FEMALE,AT-49 MALE,AT-50,AT-55,...,SGB-51,SGB-71,SGB-75,UP-84 F,UP-84 M,UP84_MAS_&_FEM,UP-94 FEMALE,UP-94 MALE,USTP-61,X-17
0,0.0,15470.0,161.5,208.0,179.4,231.1,321.0,404.0,0.0,0.0,...,0.0,129.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,5366.8097,67.89018,81.33048,75.364553,90.390623,135.56344,157.36168,0.0,0.0,...,0.0,129.332297,0.0,0.0,0.0,0.0,57.1,63.7,0.0,0.0
2,0.0,2810.293256,35.219025,45.268644,39.100132,50.237969,69.979036,88.202072,0.0,0.0,...,0.0,129.164812,0.0,0.0,0.0,0.0,37.178759,42.972609,0.0,0.0
3,0.0,1825.597768,26.030937,36.577202,28.914779,40.648335,51.825671,71.035562,0.0,0.0,...,0.0,128.997544,0.0,0.0,0.0,0.0,27.773791,35.661918,0.0,0.0
4,0.0,1319.133197,20.839256,31.980852,23.125115,35.552781,41.657664,62.248184,0.0,0.0,...,0.0,128.830492,0.0,0.0,0.0,0.0,20.774613,27.760431,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
123,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
124,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
126,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [37]:
linhas = pd.DataFrame()
tx_juros = 0.06
linhas['index'] = (1+tx_juros)**qx_morta.index
linhas2 = pd.DataFrame(columns=qx_morta.columns)
linhas2 = linhas['index'] * lx_morta['AMERICAN EXPERIENCE']
linhas2

0          100000.0
1           89601.8
2      88947.760621
3      90937.522026
4      94088.998227
           ...
122             0.0
123             0.0
124             0.0
125             0.0
126             0.0
Length: 127, dtype: object

In [25]:
lx_morta

,ALLG-72,AMERICAN EXPERIENCE,AT2000 (Suavizada 10%)_FEM,AT2000 (Suavizada 10%)_MAS,AT-2000 FEMALE,AT-2000 MALE,AT-49 FEMALE,AT-49 MALE,AT-50,AT-55,...,SGB-51,SGB-71,SGB-75,UP-84 F,UP-84 M,UP84_MAS_&_FEM,UP-94 FEMALE,UP-94 MALE,USTP-61,X-17
0,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,...,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000
1,100000.0,84530.0,99838.5,99792.0,99820.6,99768.9,99679.0,99596.0,100000.0,100000.0,...,100000.0,99870.5,100000.0,100000.0,100000.0,100000.0,100000.0,100000.0,100000.0,100000.0
2,100000.0,79163.1903,99770.60982,99710.66952,99745.235447,99678.509377,99543.43656,99438.63832,100000.0,100000.0,...,100000.0,99741.167702,100000.0,100000.0,100000.0,100000.0,99942.9,99936.3,100000.0,100000.0
3,100000.0,76352.897044,99735.390795,99665.400876,99706.135315,99628.271408,99473.457524,99350.436248,100000.0,100000.0,...,100000.0,99612.00289,100000.0,100000.0,100000.0,100000.0,99905.721241,99893.327391,100000.0,100000.0
4,100000.0,74527.299276,99709.359858,99628.823674,99677.220535,99587.623073,99421.631853,99279.400686,100000.0,100000.0,...,100000.0,99483.005347,100000.0,100000.0,100000.0,100000.0,99877.947451,99857.665473,100000.0,100000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
123,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
124,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
125,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
126,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0